# 1.序列填充

In [10]:
# 1.数字填充
import tensorflow as tf  # 导入所需库

s = [[1], [2, 3], [4, 5, 6]]  # 初始化填充前序列 s
print("填充前序列为\n", s)  # 显示填充前序列 s

# 填充序列并赋值给 a
a = tf.keras.preprocessing.sequence.pad_sequences(s, padding='post')
print("填充后序列为\n", a)  # 显示填充后序列 a


填充前序列为
 [[1], [2, 3], [4, 5, 6]]
填充后序列为
 [[1 0 0]
 [2 3 0]
 [4 5 6]]


# 2.序列裁剪

In [11]:
import tensorflow as tf  # 导入所需库
s = [[1, 2, 3, 9], [4, 5, 6], [7, 8]]  # 初始化剪裁前序列 s
print("剪裁前序列为\n", s)  # 显示剪裁前序列 s

# 剪裁序列并赋值给 a，
# maxlen=2: 通过设置 maxlen 参数，将序列的长度裁剪为2。如果序列的长度超过2，则保留最后的两个元素
a = tf.keras.preprocessing.sequence.pad_sequences(s, maxlen=2)
print("剪裁后序列为\n", a)  # 显示剪裁后序列 a


剪裁前序列为
 [[1, 2, 3, 9], [4, 5, 6], [7, 8], [9]]
剪裁后序列为
 [[3 9]
 [5 6]
 [7 8]
 [0 9]]


# 3.keras 搭建模型

In [3]:
# 3.最常见的 100 个单词
import tensorflow as tf  # 导入 TensorFlow 库
import numpy as np       # 导入 NumPy 库

# 构建空的网络模型 model
model = tf.keras.Sequential()

# 创建嵌入层
embedding = tf.keras.layers.Embedding(output_dim=32, input_dim=100, input_length=400)
model.add(embedding)  # 添加到网络模型 model 中

model.summary()  # 显示网络模型的参数信息

# 显示 embedding 矩阵的值
print("embeddings矩阵=\n", embedding.get_weights())

# 定义输入文本
text = "Deep learning is an important concept raised by the current sciences."

# 定义分词器对象
token = tf.keras.preprocessing.text.Tokenizer(num_words=100)
token.fit_on_texts([text])  # 分词
input = token.texts_to_sequences([text])  # 输出向量序列

# 序列填充
test_seq = tf.keras.preprocessing.sequence.pad_sequences(
    input, padding='post', maxlen=400, truncating='post'
)

# 使用向量序列应用网络模型
output_array = model.predict(test_seq)

# 输出矩阵的形状
print("输出矩阵的形状=", output_array.shape)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 400, 32)           3200      
                                                                 
Total params: 3,200
Trainable params: 3,200
Non-trainable params: 0
_________________________________________________________________
embeddings矩阵=
 [array([[-0.02878962, -0.03292129,  0.04554972, ..., -0.0058917 ,
         0.01143857,  0.0233766 ],
       [ 0.01397041, -0.01258515,  0.00929421, ..., -0.04004631,
         0.0135694 ,  0.0277424 ],
       [ 0.04916861, -0.04198183, -0.04687737, ..., -0.03828448,
         0.02139128,  0.02899126],
       ...,
       [-0.0321876 ,  0.0293329 ,  0.02029986, ..., -0.00899869,
        -0.00628114, -0.02092808],
       [-0.0257414 ,  0.03492158, -0.00921569, ..., -0.0181116 ,
        -0.03592857,  0.02451548],
       [ 0.04689746,  0.02985245, -0.04975928, ..., -0

# 4.构建 RNN 网络模型

In [4]:
# 构建 RNN 网络模型
import tensorflow as tf  # 导入所需库

# 创建空的网络模型 model
model = tf.keras.Sequential()

# 创建嵌入层并添加到 model 中
model.add(tf.keras.layers.Embedding(10, 5, input_length=6))

# 创建简单循环层并添加到 model 中
model.add(tf.keras.layers.SimpleRNN(128))

# 创建全连接层作为输出层，并添加到 model 中
model.add(tf.keras.layers.Dense(5, activation='softmax'))

# 显示网络模型的参数信息
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 6, 5)              50        
                                                                 
 simple_rnn (SimpleRNN)      (None, 128)               17152     
                                                                 
 dense (Dense)               (None, 5)                 645       
                                                                 
Total params: 17,847
Trainable params: 17,847
Non-trainable params: 0
_________________________________________________________________


# 5.构建 LSTM 网络

In [5]:
import tensorflow as tf  # 导入所需库

# 创建空的网络模型 model
model = tf.keras.Sequential()

# 创建嵌入层并添加到 model 中
model.add(tf.keras.layers.Embedding(10, 5, input_length=6))

# 创建长短期记忆层（LSTM）并添加到 model 中
model.add(tf.keras.layers.LSTM(128))

# 创建全连接层作为输出层，并添加到 model 中
model.add(tf.keras.layers.Dense(5, activation='softmax'))

# 显示网络模型的参数信息
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 6, 5)              50        
                                                                 
 lstm (LSTM)                 (None, 128)               68608     
                                                                 
 dense_1 (Dense)             (None, 5)                 645       
                                                                 
Total params: 69,303
Trainable params: 69,303
Non-trainable params: 0
_________________________________________________________________
